# Generated by Django 5.0.3 on 2024-03-29 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_devise'),
        ('devises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='devise',
            field=models.ForeignKey(default='EUR', on_delete=django.db.models.deletion.CASCADE, to='devises.devise'),
        ),
    ]
