# Generated by Django 5.0.3 on 2024-04-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='est_vip',
            field=models.BooleanField(default=False),
        ),
    ]
