# Generated by Django 5.0.3 on 2024-04-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_est_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='categorie_compte',
            field=models.CharField(choices=[('Client', 'Client'), ('Supplier', 'Supplier')], max_length=10),
        ),
    ]
